### ISSUE TITLE
sd_root is created with the wrong permissions

### ISSUE THREAD

**Issue by ghost** [ThatNerdyPikachu/LaunchpadNX#4]
after making a symlink for the pacman binary to be found, seen this:
```
$ ./launchpad
welcome to launchpadnx v2, where we go play with our devices!
i'm your host, the magical program that lives inside your computer~
(uhh, sorry... back to launching!)

now here comes the fun part, selecting your features!
here are your feature choices (note: as usual, atmosphere's base is selected by default):
1: checkpoint (a save manager)
2: hbmenu
3: layeredfs (game mods)
4: sigpatches
5: sys-ftpd (a background ftp server)
6: tinfoil (a title manager)
please type the numbers of the features that you want, seperated by spaces (or type 'all' to compile everything): 1 2 4 6
do you need nogc? (y/n): n

running pacman -Syu...
installing hekate's dependencies...
cloning hekate...
building hekate...
copying files...
an error occured while creating sd_root/bootloader/sys:
panic: mkdir sd_root/bootloader: permission denied

goroutine 1 [running]:
main.errCheck(0x862d20, 0xc420149600, 0x82483c, 0x1f, 0x863600, 0xc4201cabd0)
        C:/Users/Riley/go/src/github.com/ThatNerdyPikachu/LaunchpadNX/launchpad.go:37 +0xfe
main.main()
        C:/Users/Riley/go/src/github.com/ThatNerdyPikachu/LaunchpadNX/launchpad.go:268 +0x13d2
$  ls -ld sd_root
d--------- 2 user group 4096 Sep 15 23:01 sd_root
```

**Comment by ThatNerdyPikachu** [comment]
Fixed in 2.1
